# This is a basic workflow to help you get started with Actions

name: Generate Table of Content

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths:
      - '**.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "generate"
  generate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2
      
      - name: Setup Go environment
        uses: actions/setup-go@v2.1.3
        with:
          go-version: '1.16.5'

      - name: Install gh-md-toc
        run: go install "github.com/ekalinin/github-markdown-toc.go/cmd/gh-md-toc@latest"
          
      - name: Generate table of content
        run: |
          gh-md-toc --hide-header --hide-footer --depth=1 article/*.md | sort -u > README.md
          
      - uses: stefanzweifel/git-auto-commit-action@v4.11.0
        with:
          commit_message: Auto update markdown TOC
